# Generated by Django 4.0.4 on 2022-05-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=122),
        ),
    ]
