# Generated by Django 4.0.4 on 2022-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_contactno_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=122)),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=122)),
                ('qualification', models.CharField(max_length=122)),
                ('experience', models.CharField(max_length=122)),
                ('company', models.CharField(max_length=122)),
                ('skills', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
