# Generated by Django 4.0.4 on 2022-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('fname', models.CharField(max_length=122)),
                ('mname', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=122)),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=122)),
                ('department', models.CharField(max_length=122)),
                ('designation', models.CharField(max_length=122)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
