# Generated by Django 4.0.4 on 2022-05-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
