# Generated by Django 4.0.4 on 2022-06-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_employee_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
