# Generated by Django 4.0.4 on 2022-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
