# Generated by Django 4.0.4 on 2022-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
