# Generated by Django 4.0.4 on 2022-06-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_jobseeker_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='resume/'),
        ),
    ]
